all: ./lib/* ./pages/*
	lessc ./pages/home.less ../style.css
	lessc ./lib/generic.less ../publications/style.css
	lessc ./lib/generic.less ../cv/style.css
	lessc ./lib/generic.less ../media/style.css
